"""
This type stub file was generated by pyright.
"""

from .caseconverter import CaseConverter

class Camel(CaseConverter):
    def define_boundaries(self): # -> None:
        ...
    
    def prepare_string(self, s):
        ...
    
    def mutate(self, c):
        ...
    


def camelcase(s, **kwargs): # -> str:
    """Convert a string to camel case.

    Example

      Hello World => helloWorld

    """
    ...

