"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "helloWorld"), ("helloWorld", "helloWorld"), ("Hello-World", "helloWorld"), ("HELLO-WORLD", "helloWorld"), ("Hello world", "helloWorld"), ("Hello   World", "helloWorld"), ("Hello -__  World", "helloWorld"), (" hello world ", "helloWorld"), ("hellO", "hellO"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "theQuickBrownFoxJumpedOverTheLaZyDoG"), ("heLlo WoRld", "heLloWoRld")])
def test_camel_with_default_args(input, output): # -> None:
    ...

