"""
This type stub file was generated by pyright.
"""

from .caseconverter import CaseConverter

class Cobol(CaseConverter):
    JOIN_CHAR = ...
    def define_boundaries(self): # -> None:
        ...
    
    def convert(self): # -> str:
        ...
    
    def mutate(self, c):
        ...
    


def cobolcase(s, **kwargs): # -> str:
    """Convert a string to cobol case

    Example

      Hello World => HELLO-WORLD

    """
    ...

