"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "HELLO-WORLD"), ("helloWorld", "HELLO-WORLD"), ("Hello-World", "HELLO-WORLD"), ("HELLO-WORLD", "HELLO-WORLD"), ("Hello world", "HELLO-WORLD"), ("Hello   World", "HELLO-WORLD"), ("Hello -__  World", "HELLO-WORLD"), (" hello world ", "HELLO-WORLD"), ("hellO", "HELL-O"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "THE-QUICK-BROWN-FOX-JUMPED-OVER-THE-LA-ZY-DO-G"), ("heLlo WoRld", "HE-LLO-WO-RLD")])
def test_cobol_with_default_args(input, output): # -> None:
    ...

