"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "helloworld"), ("helloWorld", "helloworld"), ("Hello-World", "helloworld"), ("HELLO-WORLD", "helloworld"), ("Hello world", "helloworld"), ("Hello   World", "helloworld"), ("Hello -__  World", "helloworld"), (" hello world ", "helloworld"), ("hellO", "hello"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "thequickbrownfoxjumpedoverthelazydog"), ("heLlo WoRld", "helloworld")])
def test_flat_with_default_args(input, output): # -> None:
    ...

