"""
This type stub file was generated by pyright.
"""

from typing import override

from .caseconverter import CaseConverter

class Flat(CaseConverter):
    @override
    def define_boundaries(self) -> None: ...

def flatcase(s: str, **kwargs: object) -> str: ...
