"""
This type stub file was generated by pyright.
"""

from .caseconverter import CaseConverter

class Kebab(CaseConverter):
    JOIN_CHAR = ...
    def define_boundaries(self): # -> None:
        ...
    
    def prepare_string(self, s):
        ...
    
    def mutate(self, c):
        ...
    


def kebabcase(s, **kwargs): # -> str:
    """Convert a string to kebab case

    Example

        Hello World => hello-world

    """
    ...

