"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "hello-world"), ("helloWorld", "hello-world"), ("Hello-World", "hello-world"), ("HELLO-WORLD", "hello-world"), ("Hello world", "hello-world"), ("Hello   World", "hello-world"), ("Hello -__  World", "hello-world"), (" hello world ", "hello-world"), ("hellO", "hell-o"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "the-quick-brown-fox-jumped-over-the-la-zy-do-g"), ("heLlo WoRld", "he-llo-wo-rld")])
def test_kebab_with_default_args(input, output): # -> None:
    ...

