"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "HELLO_WORLD"), ("helloWorld", "HELLO_WORLD"), ("Hello-World", "HELLO_WORLD"), ("HELLO-WORLD", "HELLO_WORLD"), ("Hello world", "HELLO_WORLD"), ("Hello   World", "HELLO_WORLD"), ("Hello -__  World", "HELLO_WORLD"), (" hello world ", "HELLO_WORLD"), ("hellO", "HELL_O"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "THE_QUICK_BROWN_FOX_JUMPED_OVER_THE_LA_ZY_DO_G"), ("heLlo WoRld", "HE_LLO_WO_RLD"), ("HelloXWorld", "HELLO_X_WORLD")])
def test_macro_with_default_args(input, output): # -> None:
    ...

@pytest.mark.parametrize("input, output", [("IP Address", "IP_ADDRESS"), ("Hello IP Address", "HELLO_IP_ADDRESS")])
def test_macro_with_delims_only(input, output): # -> None:
    ...

