"""
This type stub file was generated by pyright.
"""

from .caseconverter import CaseConverter

class Macro(CaseConverter):
    JOIN_CHAR = ...
    def __init__(self, *args, delims_only=..., **kwargs) -> None:
        ...
    
    def define_boundaries(self): # -> None:
        ...
    
    def convert(self): # -> str:
        ...
    
    def mutate(self, c):
        ...
    


def macrocase(s, **kwargs): # -> str:
    """Convert a string to macro case

    Example

        Hello World => HELLO_WORLD

    """
    ...

