"""
This type stub file was generated by pyright.
"""

from typing import override

from .caseconverter import CaseConverter

class Pascal(CaseConverter):
    @override
    def init(self, input_buffer, output_buffer) -> None: ...
    @override
    def define_boundaries(self) -> None: ...

def pascalcase(s: str, **kwargs: object) -> str: ...
