"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "HelloWorld"), ("helloWorld", "HelloWorld"), ("Hello-World", "HelloWorld"), ("HELLO-WORLD", "HelloWorld"), ("Hello world", "HelloWorld"), ("Hello   World", "HelloWorld"), ("Hello -__  World", "HelloWorld"), (" hello world ", "HelloWorld"), ("hellO", "HellO"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "TheQuickBrownFoxJumpedOverTheLaZyDoG"), ("heLlo WoRld", "HeLloWoRld"), ("helloWORLD", "HelloWORLD")])
def test_pascal_with_default_args(input, output): # -> None:
    ...

