"""
This type stub file was generated by pyright.
"""

import pytest
from . import *

@pytest.mark.parametrize("input, output", [("Hello, world!", "hello_world"), ("helloWorld", "hello_world"), ("Hello-World", "hello_world"), ("HELLO-WORLD", "hello_world"), ("Hello world", "hello_world"), ("Hello   World", "hello_world"), ("Hello -__  World", "hello_world"), (" hello world ", "hello_world"), ("hellO", "hell_o"), (r"the quick !b@rown fo%x jumped over the laZy Do'G", "the_quick_brown_fox_jumped_over_the_la_zy_do_g"), ("heLlo WoRld", "he_llo_wo_rld")])
def test_snake_with_default_args(input, output): # -> None:
    ...

