"""
This type stub file was generated by pyright.
"""

from typing import override

from .caseconverter import CaseConverter

class Snake(CaseConverter):
    JOIN_CHAR: str = "_"
    @override
    def define_boundaries(self) -> None: ...
    @override
    def prepare_string(self, s: str) -> str: ...
    @override
    def mutate(self, c: str) -> str: ...

def snakecase(s: str, **kwargs: object) -> str: ...
