"""
This type stub file was generated by pyright.
"""

import pytest

@pytest.mark.parametrize("input, output", [("Hello, world!", "Hello World"), ("helloWorld", "Hello World"), ("Hello-World", "Hello World"), ("HELLO-WORLD", "Hello World"), ("Hello world", "Hello World"), ("Hello   World", "Hello World"), ("Hello -__  World", "Hello World"), (" hello world ", "Hello World"), (r"the quick !b@rown fo%x jumped over the lazy Dog", "The Quick Brown Fox Jumped Over The Lazy Dog"), ("this is a long title", "This Is A Long Title")])
def test_title_with_default_args(input, output): # -> None:
    ...

