"""
This type stub file was generated by pyright.
"""

from .caseconverter import CaseConverter
from .boundaries import BoundaryHandler, OnDelimeterUppercaseNext

class Title(CaseConverter):
    def init(self, input_buffer, output_buffer): # -> None:
        ...
    
    def define_boundaries(self): # -> None:
        ...
    
    def prepare_string(self, s):
        ...
    
    def mutate(self, c):
        ...
    


class OnDelimeterPreserveAndUpperNext(OnDelimeterUppercaseNext):
    def __init__(self, delimiters) -> None:
        ...
    
    def handle(self, pc, cc, input_buffer, output_buffer): # -> None:
        ...
    


class OnUpperPrecededByLowerAddSpace(BoundaryHandler):
    def is_boundary(self, pc, c): # -> Literal[False]:
        ...
    
    def handle(self, pc, cc, input_buffer, output_buffer): # -> None:
        ...
    


def titlecase(s, **kwargs): # -> str:
    """Convert a string to title case.

    Example:
        Hello world => Hello World
        hello-world => Hello World
        helloWorld => Hello World
    """
    ...

